### ISSUE TITLE
Unable to reproduce expected results on provided datasets

### ISSUE THREAD

**Issue by koapa13** [ZEISS/iPad_TrueDepth_Issue_Eval#1]
After checking out origin/main (SHA 2439105) and running the calibrate_front_camera.py and evaluate_depth.py scripts on the provided datasets in this repository, I get differing results from the ones in the paper.

Here is the output from the calibrate_front_camera.py script:
```
Calibrating: FrontCamCalibrationDataset/iPadPro12_4gen_iOS15
Detected a total number of 1167 corners in 25 images
Calibrated focal length: 613.38px
Factory focal length: 595.34px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 4.82px
Difference to factory calibration: 3.03% 

Calibrating: FrontCamCalibrationDataset/iPadPro12_5gen_iOS15
Detected a total number of 852 corners in 26 images
Calibrated focal length: 606.23px
Factory focal length: 565.12px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 4.41px
Difference to factory calibration: 7.27% 

Calibrating: FrontCamCalibrationDataset/iPhone11Pro_iOS14
Detected a total number of 1055 corners in 20 images
Calibrated focal length: 459.73px
Factory focal length: 436.50px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 4.62px
Difference to factory calibration: 5.32% 
```

Each of the calibrated focal lengths deviates significantly from the expected ones:

> <!DOCTYPE html><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(201, 209, 217); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">The results for the provided datasets should be:</p>
> 
> Device | Factory focal length [px] | Calibrated focal length [px] | Difference in [%]
> -- | -- | -- | --
> iPhone11Pro | 436.5 | 434.61 | -0.43 %
> iPadPro 12.9 4gen | 595.34 | 602.38 | 1.18 %
> iPadPro 12.9 5gen | 565.12 | 530.04 | -6.21 %
> 
> <br class="Apple-interchange-newline">

The evaluate_depth.py plots also show that the estimated Aruco board depths deviate from the expected. Here is a comparison of the iPhone11Pro_iOS14 error_plot_depth_rgb_1233714.png.svg plot as generated after running the script myself, vs the expected output at https://github.com/ZEISS/iPad_TrueDepth_Issue_Eval/blob/main/DepthEvalDataset/iPhone11Pro_iOS14/result_plots_factory_calib/error_plot_depth_rgb_1233714.png.svg:

**Output:**
![error_plot_depth_rgb_1233714 png](https://user-images.githubusercontent.com/4098530/201117394-fbafcbb9-eec9-407f-b967-8d2342e6655d.svg)
**Expected:**
![error_plot_depth_rgb_1233714 png](https://user-images.githubusercontent.com/4098530/201117520-49ff611f-b14a-4e6d-8421-165e10201b81.svg)

Please see the attached output files for each of these datasets, along with the requirements.txt for the software versions of each package I have installed.

[CalibrationOutput.zip](https://github.com/ZEISS/iPad_TrueDepth_Issue_Eval/files/9981761/CalibrationOutput.zip)

**Comment by urbste** [comment]
@koapa13  Hi. Thank you for your question. In your *.zip file I could not find your python environment setting. Maybe it has something todo with the opencv version. Could you attach that so I can try to reproduce your numbers?

**Comment by koapa13** [comment]
Thank you for letting me know that the requirements.txt file was missing, and for looking into this. I've attached it here instead:
[requirements.txt](https://github.com/ZEISS/iPad_TrueDepth_Issue_Eval/files/10058631/requirements.txt)

**Comment by koapa13** [comment]
If you could share the package versions for each dependency that you are using, I will try installing the same versions to see if that reproduces the same results.

**Comment by urbste** [comment]
Hi @koapa13 . I identified the problem. The newest opencv-contrib (4.6) has a new aruco interface and updated aruco marker detection. This leads obviously to some issues that I need to figure out. You can reproduce the results by downgrading to opencv-contrib-python==4.5.4.60.
```
pip install --force-reinstall opencv-contrib-python==4.5.4.60
```

**Comment by koapa13** [comment]
Thanks for finding the cause of the discrepancy. I downgraded to opencv-contrib-python 4.5.4.60, and the results are much closer to expected now. There are still some discrepancies, but the deltas are fairly small. Here are the results I get after re-running the calibration script:

```
% python calibrate_front_camera.py 
Calibrating: FrontCamCalibrationDataset/iPadPro12_4gen_iOS15
Detected a total number of 971 corners in 23 images
Calibrated focal length: 601.86px
Factory focal length: 595.34px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 0.53px
Difference to factory calibration: 1.09% 

Calibrating: FrontCamCalibrationDataset/iPadPro12_5gen_iOS15
Detected a total number of 697 corners in 23 images
Calibrated focal length: 528.97px
Factory focal length: 565.12px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 0.52px
Difference to factory calibration: -6.40% 

Calibrating: FrontCamCalibrationDataset/iPhone11Pro_iOS14
Detected a total number of 967 corners in 18 images
Calibrated focal length: 434.10px
Factory focal length: 436.50px
Distortion coefficients:  [0. 0. 0. 0. 0.]
Reprojection error: 0.59px
Difference to factory calibration: -0.55%
```
